ALTER TABLE score.tScoreDia
 ADD nQFrenada INT UNSIGNED NOT NULL DEFAULT '0' AFTER nCurva,
 ADD nQAceleracion INT UNSIGNED NOT NULL DEFAULT '0',
 ADD nQVelocidad INT UNSIGNED NOT NULL DEFAULT '0',
 ADD nQCurva INT UNSIGNED NOT NULL DEFAULT '0';
